import { useEffect, useState } from 'react';
import { ChevronRight, Search } from 'lucide-react';
type Service = { id: string; name: string; category?: string; platformId: string; pricePer1000: number };
type Props = { services: Service[]; query: string; setQuery: (value: string) => void; loading: boolean; onSelect: (service: Service) => void; platforms?: string[]; activePlatform?: string; onPlatformChange?: (platform: string) => void };
export default function ServicesOptimized({ services, query, setQuery, loading, onSelect, platforms = [], activePlatform = '', onPlatformChange }: Props) {
  const [visibleCount, setVisibleCount] = useState(60);
  useEffect(() => { setVisibleCount(60); }, [query, activePlatform]);
  const visibleServices = services.slice(0, visibleCount);
  const showDirectory = !activePlatform && !query.trim();
  return <div className="content services-content"><div className="services-layout"><aside className="services-subnav"><button className={!activePlatform ? 'active' : ''} onClick={() => onPlatformChange?.('')}><span className="platform all-platforms">All</span>All active services</button>{platforms.map(platform => <button key={platform} className={activePlatform === platform ? 'active' : ''} onClick={() => onPlatformChange?.(platform)}><span className={`platform ${platform}`}>{platform.slice(0, 1).toUpperCase()}</span>{platform}<small>{services.filter(service => service.platformId === platform).length}</small></button>)}</aside><main className="services-main"><div className="page-intro"><div>{activePlatform&&<button className="back-link" onClick={() => onPlatformChange?.('')}><span>←</span> Back to platforms</button>}<span className="eyebrow">CATALOG</span><h2>{activePlatform ? `${activePlatform} services.` : 'Choose a platform.'}</h2><p>{activePlatform ? `${services.length} active services available.` : 'Select a social media platform to view its services.'}</p></div><div className="search"><Search size={17}/><input placeholder="Search services" value={query} onChange={event => setQuery(event.target.value)}/></div></div>{loading ? <div className="empty">Loading your catalog...</div> : showDirectory ? <div className="platform-directory">{platforms.map(platform => <button className="platform-directory-card" key={platform} onClick={() => onPlatformChange?.(platform)}><span className={`platform ${platform}`}>{platform.slice(0, 1).toUpperCase()}</span><strong>{platform}</strong><small>{services.filter(service => service.platformId === platform).length} services</small><ChevronRight size={17}/></button>)}</div> : <><div className="service-grid">{visibleServices.map(service => <button className="service-card" key={service.id} onClick={() => onSelect(service)}><div className={`platform ${service.platformId}`}>{service.platformId.slice(0, 1).toUpperCase()}</div><span className="category">{service.category || service.platformId}</span><h3>{service.name}</h3><div className="service-meta"><span>From KES {Number(service.pricePer1000 || 0).toLocaleString(undefined, { minimumFractionDigits: 2, maximumFractionDigits: 2 })} / 1k</span><ChevronRight size={16}/></div></button>)}{!services.length&&<div className="empty">No services found. Try another search.</div>}</div>{visibleCount < services.length && <button className="btn outline service-load-more" onClick={() => setVisibleCount(count => count + 60)}>Load more services ({services.length - visibleCount} remaining)</button>}</>}</main></div></div>;
}
